# Generated by Django 5.0.1 on 2024-07-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Трехместный')], max_length=50)),
                ('category', models.CharField(choices=[('standard', 'Стандарт'), ('deluxe', 'Делюкс'), ('luxury', 'Люкс')], max_length=50)),
                ('has_child_bed', models.BooleanField(default=False)),
            ],
        ),
    ]
